### ISSUE TITLE
Option to provide chunk counts as well as lengths?

### ISSUE THREAD

**Issue by sahwa** [YaolingYang/SparsePainter#1]
Hello, thanks for the nice program. I was wondering if there was any way to provide the expected counts of chunk matching between donors and recipients, as an alternative to the expected length of matching - as counts generally seem to work better when doing PCA?

Thanks!

Sam

**Comment by YaolingYang** [comment]
Hi Sam,

Thanks for your suggestion! I have updated SparsePainter to output the chunk count, please find the changelog at the bottom of the page. Note that we output the chunk length and chunk count between each local ancestry and target samples (in haplotype). If you prefer the match between donors and recepients, you could set each donor as a different population through -popfile.

For PCA and clustering, from our experience, chunk length may work as well as or better than chunk counts.

Best regards,
Yaoling

**Comment by sahwa** [comment]
Hi, 

That's great, thanks so much for the fast response! 

Best,

Sam
